export interface R9Result { tf: string; policy: string; cost: string }
export interface R9Template extends R9Result { match: string[] }

export const R9_EXAMPLES = [
  { label: "Staging for payments API", prompt: "A staging environment for the payments API — Postgres, Redis, two app nodes, EU only, torn down after 48 hours" },
  { label: "GPU lease for fine-tuning", prompt: "Four A100 GPUs for a fine-tuning run, on our own cluster, maximum eight hours, charged to data-platform" },
  { label: "On-prem Proxmox VM", prompt: "A hardened Proxmox VM for the SAP integration test, on-prem only, CIS benchmarked" },
  { label: "Agent sandbox", prompt: "An isolated sandbox for a coding agent to verify a pull request, no production data, two hours" },
];

export const R9_TEMPLATES: R9Template[] = [
  {
    match: ["gpu", "a100", "h100", "fine-tun", "training", "train"],
    tf: `<span class="c-com"># generated by R9 · module catalogue: acme/gpu-lease v2.4</span>
<span class="c-key">resource</span> <span class="c-str">"realm9_gpu_lease"</span> <span class="c-str">"finetune"</span> {
  project      = <span class="c-str">"data-platform"</span>
  accelerator  = <span class="c-str">"nvidia-a100-80gb"</span>
  count        = <span class="c-num">4</span>
  placement    = <span class="c-str">"onprem/gpu-01"</span>   <span class="c-com"># owned cluster preferred</span>
  ttl          = <span class="c-str">"8h"</span>
  preemptible  = <span class="c-key">true</span>
  scheduler    = <span class="c-str">"kai"</span>              <span class="c-com"># placement delegated</span>

  budget {
    ceiling_usd = <span class="c-num">1200</span>
    charge_to   = <span class="c-str">"data-platform"</span>
  }
  labels = {
    workload = <span class="c-str">"fine-tune"</span>
    owner    = <span class="c-str">"team/data-platform"</span>
  }
}`,
    policy: `<span class="c-ok">✓ gpu-max-ttl</span>          8h ≤ 12h limit
<span class="c-ok">✓ gpu-requires-budget</span>  ceiling set
<span class="c-ok">✓ onprem-first</span>         owned capacity preferred
<span class="c-ok">✓ preempt-over-quota</span>   marked preemptible
<span class="c-warn">⚑ quota-borrow</span>        4 GPU over deserved quota
   <span class="c-dim">→ requires approval from @ml-platform-leads</span>
<span class="c-ok">✓ trufflehog</span>           no secrets detected

<span class="c-dim">1 gate · 0 blocks · apply pending approval</span>`,
    cost: `ITEM                        RATE        TOTAL
4 × A100-80GB · 8h        <span class="c-num">$14.60</span>/hr    <span class="c-num">$467.20</span>
attached storage 2TB       <span class="c-num">$0.09</span>/hr      <span class="c-num">$5.76</span>
egress (est.)                  —        <span class="c-num">$12.00</span>
                                    <span class="c-dim">─────────</span>
lease total                          <span class="c-num">$484.96</span>

<span class="c-dim">budget ceiling</span>       <span class="c-num">$1,200</span>
<span class="c-dim">remaining after</span>      <span class="c-ok">$715.04</span>
<span class="c-dim">charged to</span>           data-platform`,
  },
  {
    match: ["proxmox", "on-prem", "onprem", "vcenter", "vm", "sap", "bare metal", "hardened"],
    tf: `<span class="c-com"># generated by R9 · module catalogue: acme/proxmox-vm v1.9</span>
<span class="c-key">resource</span> <span class="c-str">"proxmox_vm_qemu"</span> <span class="c-str">"sap_integration"</span> {
  name        = <span class="c-str">"sap-int-01"</span>
  target_node = <span class="c-str">"pve-ldn-04"</span>
  clone       = <span class="c-str">"rhel9-cis-hardened"</span>   <span class="c-com"># CIS L2 baseline</span>
  cores       = <span class="c-num">8</span>
  memory      = <span class="c-num">32768</span>
  disk { size = <span class="c-str">"200G"</span>  storage = <span class="c-str">"ceph-nvme"</span> }
  network { bridge = <span class="c-str">"vmbr-int"</span>  model = <span class="c-str">"virtio"</span> }
}

<span class="c-key">resource</span> <span class="c-str">"realm9_lease"</span> <span class="c-str">"sap_integration"</span> {
  resource_ref = proxmox_vm_qemu.sap_integration.id
  ttl          = <span class="c-str">"14d"</span>
  data_class   = <span class="c-str">"internal"</span>
  cis_profile  = <span class="c-str">"rhel9-level2"</span>
  egress       = <span class="c-str">"deny-all"</span>          <span class="c-com"># on-prem only</span>
}`,
    policy: `<span class="c-ok">✓ cis-baseline</span>         rhel9-level2 applied
<span class="c-ok">✓ no-public-egress</span>     deny-all enforced
<span class="c-ok">✓ lease-has-ttl</span>        14d ≤ 30d limit
<span class="c-ok">✓ data-residency</span>       ldn-dc1, UK only
<span class="c-ok">✓ checkov</span>              18/18 passed
<span class="c-ok">✓ trufflehog</span>           no secrets detected

<span class="c-ok">0 gates · 0 blocks · ready to apply</span>`,
    cost: `ITEM                        RATE        TOTAL
proxmox 8vCPU/32GB · 14d  <span class="c-num">$0.21</span>/hr     <span class="c-num">$70.56</span>
ceph-nvme 200GB · 14d     <span class="c-num">$0.03</span>/hr     <span class="c-num">$10.08</span>
                                    <span class="c-dim">─────────</span>
lease total                           <span class="c-num">$80.64</span>

<span class="c-dim">note</span>  on-prem capacity is amortised, not billed.
      <span class="c-ok">Realm9 does not meter hardware you own.</span>`,
  },
  {
    match: ["sandbox", "agent", "pull request", "pr ", "verify", "isolated"],
    tf: `<span class="c-com"># generated by R9 · module catalogue: acme/agent-sandbox v0.8</span>
<span class="c-key">resource</span> <span class="c-str">"realm9_sandbox"</span> <span class="c-str">"pr_verify"</span> {
  principal   = <span class="c-str">"agent/pr-reviewer"</span>
  isolation   = <span class="c-str">"microvm"</span>
  image       = <span class="c-str">"acme/ci-base:node22"</span>
  cpu         = <span class="c-num">4</span>
  memory_gb   = <span class="c-num">8</span>
  ttl         = <span class="c-str">"2h"</span>

  network {
    egress_allow = [<span class="c-str">"registry.acme.internal"</span>, <span class="c-str">"github.com"</span>]
    egress_deny  = [<span class="c-str">"*"</span>]
  }
  data {
    class          = <span class="c-str">"none"</span>
    production_ref = <span class="c-key">false</span>   <span class="c-com"># no prod data reachable</span>
  }
  budget { ceiling_usd = <span class="c-num">50</span> }
}`,
    policy: `<span class="c-ok">✓ agent-requires-owner</span>   @t.nakamura
<span class="c-ok">✓ agent-no-production</span>    production_ref = false
<span class="c-ok">✓ sandbox-max-ttl</span>        2h ≤ 4h limit
<span class="c-ok">✓ egress-allowlist</span>       2 hosts permitted
<span class="c-ok">✓ budget-ceiling</span>         $50 within agent quota
<span class="c-ok">✓ isolation-microvm</span>      hardware boundary

<span class="c-ok">0 gates · 0 blocks · auto-approved</span>
<span class="c-dim">policy: ephemeral-auto · no human review required</span>`,
    cost: `ITEM                        RATE        TOTAL
microvm 4vCPU/8GB · 2h     <span class="c-num">$0.14</span>/hr      <span class="c-num">$0.28</span>
governed actions × 6      <span class="c-num">$0.004</span>       <span class="c-num">$0.02</span>
                                    <span class="c-dim">─────────</span>
lease total                            <span class="c-num">$0.30</span>

<span class="c-dim">agent budget</span>    $212 of $2,000 used this month
<span class="c-dim">after lease</span>     <span class="c-ok">$1,787.70 remaining</span>`,
  },
];

export const R9_DEFAULT: R9Result = {
  tf: `<span class="c-com"># generated by R9 · module catalogue: acme/app-env v3.1</span>
<span class="c-key">module</span> <span class="c-str">"payments_staging"</span> {
  source = <span class="c-str">"acme/app-env/aws"</span>
  region = <span class="c-str">"eu-west-1"</span>          <span class="c-com"># EU-only per policy</span>

  app_nodes  = <span class="c-num">2</span>
  instance   = <span class="c-str">"t3.large"</span>

  postgres { version = <span class="c-str">"16"</span>  size = <span class="c-str">"db.t4g.medium"</span> }
  redis    { version = <span class="c-str">"7"</span>   size = <span class="c-str">"cache.t4g.small"</span> }

  tags = {
    service = <span class="c-str">"payments-api"</span>
    env     = <span class="c-str">"staging"</span>
    owner   = <span class="c-str">"team/payments"</span>
  }
}

<span class="c-key">resource</span> <span class="c-str">"realm9_lease"</span> <span class="c-str">"payments_staging"</span> {
  resource_ref = module.payments_staging.id
  ttl          = <span class="c-str">"48h"</span>
  on_expiry    = <span class="c-str">"destroy"</span>
  charge_to    = <span class="c-str">"team/payments"</span>
}`,
  policy: `<span class="c-ok">✓ region-allowlist</span>      eu-west-1 permitted
<span class="c-ok">✓ lease-has-ttl</span>         48h ≤ 7d limit
<span class="c-ok">✓ teardown-on-expiry</span>    destroy configured
<span class="c-ok">✓ required-tags</span>         service, env, owner present
<span class="c-warn">⚑ CKV_AWS_23</span>            security group rule lacks description
   <span class="c-dim">→ non-blocking, tracked as R9-2211</span>
<span class="c-ok">✓ trufflehog</span>            no secrets detected
<span class="c-ok">✓ trivy</span>                 base images clean

<span class="c-dim">1 warning · 0 gates · 0 blocks · ready to apply</span>`,
  cost: `ITEM                        RATE        TOTAL
2 × t3.large · 48h        <span class="c-num">$0.083</span>/hr     <span class="c-num">$7.97</span>
db.t4g.medium · 48h        <span class="c-num">$0.065</span>/hr     <span class="c-num">$3.12</span>
cache.t4g.small · 48h      <span class="c-num">$0.034</span>/hr     <span class="c-num">$1.63</span>
storage + egress (est.)          —        <span class="c-num">$2.40</span>
                                    <span class="c-dim">─────────</span>
lease total                           <span class="c-num">$15.12</span>

<span class="c-dim">team budget</span>      $4,180 of $12,000 used
<span class="c-dim">after lease</span>      <span class="c-ok">$7,804.88 remaining</span>
<span class="c-dim">vs. untracked</span>    this would have been untagged`,
};
